server:
  port: 8082
spring:
  application:
    name: consumer-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
feign:
  hystrix:
    enabled : true
ribbon:
  ReadTimeout: 2000
  ConnectTimeout: 500
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
