server:
  port: 10010
eureka:
  client:
    service-url:
      defaultZone : http://127.0.0.1:10086/eureka
spring:
  application:
    name: gateway-service
zuul:
  routes:
    user-service : /user/**
  ignored-services:
    - consumer-service
ribbon:
  ReadTimeout: 2000
  ConnectTimeout: 500
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000

